# Generated by Django 5.2 on 2025-12-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='voice',
            field=models.CharField(choices=[('en-GB-Neural2-A', 'British Female (Elegant)'), ('en-GB-Neural2-B', 'British Male (Distinguished)'), ('en-GB-Neural2-C', 'British Female (Warm)'), ('en-GB-Neural2-D', 'British Male (Authoritative)'), ('en-US-Neural2-A', 'American Female'), ('en-US-Neural2-D', 'American Male')], default='en-GB-Neural2-A', max_length=50),
        ),
    ]
