# Generated by Django 5.2 on 2025-12-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_character_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='voice',
            field=models.CharField(choices=[('en-GB-Neural2-A', 'British Female - Clear & Professional'), ('en-GB-Neural2-C', 'British Female - Warm & Friendly'), ('en-GB-Neural2-F', 'British Female - Young & Energetic'), ('en-GB-Neural2-B', 'British Male - Deep & Mature'), ('en-GB-Neural2-D', 'British Male - Authoritative'), ('en-US-Neural2-A', 'American Female - Clear'), ('en-US-Neural2-C', 'American Female - Warm'), ('en-US-Neural2-D', 'American Male - Deep'), ('en-US-Neural2-J', 'American Male - Casual')], help_text='Google TTS voice for this character', max_length=50),
        ),
    ]
